language: python
python:
  - "3.5"
install:
  - cp contrib/env-sample .env
  - export SECRET_KEY=`python contrib/secret_gen.py`
  - pip install -q -r requirements.txt
script:
  - python manage.py test
